# A unified parameterized dockerfile to be used for building devcontainers and lightweight
# python-based images to be used in production. The purpose is to replicate in production
# (as much as possible) the development environment setup.
ARG BASE_IMAGE="ghcr.io/veil-org/devcontainers/python-3.10-buster-devcontainer-toolchain"
ARG TAG="0.1.8"

FROM ${BASE_IMAGE}:${TAG} AS base_image